we should keep ourselves in the supported releases described here https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported
useful react-native upgrade tool: https://react-native-community.github.io/upgrade-helper/?from=0.64.4&to=0.71.8

* conflict between node lib versions
stop using npm install and start using yarn install
* Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
this has been "fixed" on versions of react-native >=0.65
* Unexpected token '?'
this happened when I tried to jump to react-native 0.70.0
* Failed to transform react-native-reanimated-65-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}.
https://stackoverflow.com/a/69077685/1851150
yarn add react-native-reanimated@2.3.0-alpha.3
* attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()'on a null object reference
https://github.com/software-mansion/react-native-reanimated/issues/2369
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android
in the end I've fixed it by upgrading the reanimated version to `2.3.0-alpha.2` as opposed to `2.3.0-alpha.3`

### this was enough to upgrade react-native to 0.65.0 /\

* Failed to transform react-native-reanimated-66-jsc.aar (project :react-native-reanimated) to match attributes {artifactType=android-aar-metadata}
[[https://stackoverflow.com/a/69509098]["This issue has resolved in react-native-reanimated@2.3.0-beta.2 release."]]

** new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method
 that didn't work: https://bugsfixing.com/solved-new-nativeeventemitter-was-called-with-a-non-null-argument-without-the-required-addlistener-method/
 :/ it might be happening even for non-debug, I'm not so sure.
 LogBox at the App.js hid the warning for good :) https://github.com/michalchudziak/react-native-geolocation/issues/195#issuecomment-1260049366
* react-native 0.67.0
smooth
* react-native 0.68.0
1. I'm getting this warning /ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'./  22 times.
2. It seems like the ViewPropTypes is not directly used by our code, but by libs that we use and that are outdated. I'll leverage the [[updater too][updater tool]] to see if I can get rid of any.
3. Using the tool, the change I made was to @react-native-masked-view/masked-view upgrading it to 0.2.0 and renaming the "community" part of the package. My plan is to use it as a canary to check if we can drop to 21 warnings but it didn't work. I'll try to upgrade to the most recent version of the package.
4. <2023-05-19 sex 06:29> the warnings won't go away, but at least the package is updated :)
5. <2023-05-19 sex 06:38> still getting the warnings but now I upgraded '@react-native-async-storage/async-storage', '@react-native-clipboard/clipboard' and '@react-native-masked-view/masked-view'.
6. <2023-05-19 sex 06:54> I upgraded a bunch of libs to their recommended versions on 0.68.0, but I'm still getting the warnings. I saw they were indeed added into 0.68.0. This github issue might help https://github.com/facebook/react-native/issues/33557 and this [[https://github.com/facebook/react-native/issues/33557#issuecomment-1114498902][comment]] in particular sounds based.
7. <2023-05-19 sex 07:02> Ok, these warnings can't be solved by the current recommended versions of the libs for this package; So I'll also ignore them via LogBox and come back to it once we get everything upgraded.
8. <2023-05-19 sex 07:10> back to upgrading libs using the upgrader, I downgraded reanimated to keep it happy and now every one of them is up to date with 0.68.0 but one: react-native-gesture-handler. Upgrading it will cause the error below:
** A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
https://github.com/software-mansion/react-native-gesture-handler/issues/2168
Nice. Upgrading the compileSdk and targetSdk from 31 to 33 fixed the issue, kudos to this [[https://github.com/software-mansion/react-native-gesture-handler/issues/2168#issuecomment-1546998935][comment]].

* react-native 0.69.0
** Error: ENOENT: no such file or directory, scandir 'node_modules'
I removed the node_modules folder and run an yarn install again but it didn't work. So I ran the run-android command with a --no-jetifier flag and it seem to have worked
**  ERROR  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
1. <2023-05-19 sex 20:45> After upgrading the dependencies to 0.69.0 I was still getting this error related to ViewPropTypes. What I found is that one of our dependencies was not being maintained for the past 3 years. So the usage this lib did of ViewPropTypes became unsustainable. Is the `react-native-snap-carousel`. The lib should have at least fixed that but they didn't and the whole thing [[https://github.com/meliorence/react-native-snap-carousel/issues/982][was deprecated]].
   Removing this lib from our project fixed all the issues I was having, but it completely breaks the 'Financeiro' screen. The following error was also fixed: /ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native./
   There's a bunch of ViewPropTypes [[https://github.com/meliorence/react-native-snap-carousel/issues?q=is%3Aissue+is%3Aopen+ViewPropTypes][open issues for the repo]]  and I don't think they are going to be addressed. My last resource came from [[https://github.com/meliorence/react-native-snap-carousel/issues/981#issuecomment-1528901361][one of the comments]] in one of those issues. Which is using this other lib [[https://www.npmjs.com/package/react-native-reanimated-carousel][react-native-reanimated-carousel]] that is currently maintained and hopefully keeps the same interface.
2. <2023-05-19 sex 21:06> HELL YEAH. After a small adaptation I managed to get the new Carousel working 🕺
* react-native 0.70.0
** yntaxError: Unexpected token '?'
cmd.option(opt.name, opt.description ?? '', opt.parse || (val => val), typeof opt.default === 'function' ? opt.default(rest[0]) : opt.default);
https://github.com/facebook/react-native/issues/34768
https://github.com/react-native-community/cli/issues/1703
people is saying this is related to node version. But I'm sure I'm running node v18.16.0 which is pretty new. I wonder if react-native has its own node or something like that.
1. <2023-05-20 sáb 07:10> I might have fixed it but there is still something wrong. I pasted the error to ChatGPT, it explained that the nullish coalescing operator was introduced in node 14 and that I should try to upgrade my node version (which I did) but also clear use an alternative method to clear the cache besides the `--reset-cache` option. The way I'm currently trying to run react-native is by running ~watchman watch-del-all && react-native start --reset-cache~. It then suggested me to run a  ~rm -rf $TMPDIR/metro-*~ that would reset this "metro" folder from a $TMPDIR that is not really assigned to anything on my terminal :shrug:
   After runnng the rm -rf the application successfully ran once with ~react-native start --reset-cache~, but when I tried to ~watchman watch-del-all && react-native start --reset-cache~ it failed again with the same coalescing operator ?? error. It feels like the project is using its own node version instead of using the one I have on my machine.
   Since I didn't know what metro is or does, I also asked ChatGPT: "In the context of a React Native application, Metro is the JavaScript bundler used to package and serve the JavaScript code for your app during development. It is responsible for transforming your JavaScript code, resolving dependencies, and creating a bundle that can be executed by the JavaScript runtime on the device or emulator.". With that I tried to change the node version used by Metro by adding the following "engines" block to my package.json but it also didn't work:
#+BEGIN_SRC
  "engines": {
    "node": ">=14.x"
  }
#+END_SRC
2. <2023-05-20 sáb 07:40> It seems like I figured it out. There was two react-native versions being executed when I typed ~react-native start~. By typing it like that it would use the react-native globally installed on my local environment and it would fail with above error. Starting it with ~npx react-native start~ works because it starts the Metro from within the project's node_modules, which is what we want. The "engines" blocks is unnecessary. I'm not sure why the globally installed version of react-native wouldn't work, or why its Metro was using an obsolete version of node, but I'm ok with simply moving on. 

* react-native 0.71.0
** frozen ./gradlew clean
https://github.com/volta-cli/volta/issues/1007#issuecomment-881771029
** Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.
add ~hermesEnabled=true~ to gradle.properties
** Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
fixed removing block from android/build.gradle: https://github.com/facebook/react-native/issues/36234#issuecomment-1439770679
** Could not find com.facebook.react:react-android:.

IOS: 
First problem:  Please specify "higher minimum deployment target" dependency - solution found here - https://github.com/CocoaPods/CocoaPods/issues/7304#issuecomment-491065166
Basically I had to go to ios/Podfile and update - from platform :ios, '10.0' - to platform :ios, '13.0'
Second problem: No visible @interface for 'RCTBundleURLProvider' declares the selector 'jsBundleURLForBundleRoot:fallbackResource:' - solution found here https://stackoverflow.com/a/73048366 - 
on ios/Cappella/AppDelegate.m, replace return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil]; to return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"]; 
